/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/assets/models/ad-medica-cube.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ad-medica-cube.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light001" position={[4.076, 5.904, -1.005]} rotation={[1.89, 0.881, -2.045]} />
        <group name="Camera001" position={[7.359, 4.958, 6.926]} rotation={[1.242, 0.33, -0.76]} />
        <group name="camera" position={[0, 0, 5.988]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.01} />
        <group name="all" rotation={[2.006, -0.228, -0.515]} scale={0.01}>
          <group name="shell">
            <mesh name="cube" geometry={nodes.cube.geometry} material={materials.tex005} position={[0, 0, 96.233]} />
            <mesh name="cube_1" geometry={nodes.cube_1.geometry} material={materials.tex010} position={[0, 0, -96.233]} />
            <mesh name="cube_2" geometry={nodes.cube_2.geometry} material={materials.tex012} position={[-96.233, 0, 0]} />
            <mesh name="cube_3" geometry={nodes.cube_3.geometry} material={materials.tex003} position={[0, -96.233, 0]} />
            <mesh name="cube_4" geometry={nodes.cube_4.geometry} material={materials.tex006} position={[96.233, 0, 0]} />
            <mesh name="cube_5" geometry={nodes.cube_5.geometry} material={materials.tex008} position={[0, 96.233, 0]} />
            <mesh name="cube_inside_1_fracturepart" geometry={nodes.cube_inside_1_fracturepart.geometry} material={materials.tex003} position={[0, 0, 103.4]} />
            <mesh name="cube_inside_2_fracturepart" geometry={nodes.cube_inside_2_fracturepart.geometry} material={materials.tex011} position={[0, 0, -103.4]} />
            <mesh name="cube_inside_3_fracturepart" geometry={nodes.cube_inside_3_fracturepart.geometry} material={materials.tex004} position={[-103.4, 0, 0]} />
            <mesh name="cube_inside_4_fracturepart" geometry={nodes.cube_inside_4_fracturepart.geometry} material={materials.tex007} position={[0, -103.4, 0]} />
            <mesh name="cube_inside_5_fracturepart" geometry={nodes.cube_inside_5_fracturepart.geometry} material={materials.tex010} position={[103.4, 0, 0]} />
            <mesh name="cube_inside_6_fracturepart" geometry={nodes.cube_inside_6_fracturepart.geometry} material={materials.tex005} position={[0, 103.4, 0]} />
            <mesh name="cube_outside_1_fracturepart" geometry={nodes.cube_outside_1_fracturepart.geometry} material={materials.tex001} position={[0, 113.885, 0]} />
            <mesh name="cube_outside_2_fracturepart" geometry={nodes.cube_outside_2_fracturepart.geometry} material={materials.tex006} position={[113.885, 0, 0]} />
            <mesh name="cube_outside_3_fracturepart" geometry={nodes.cube_outside_3_fracturepart.geometry} material={materials.tex012} position={[0, -113.885, 0]} />
            <mesh name="cube_outside_4_fracturepart" geometry={nodes.cube_outside_4_fracturepart.geometry} material={materials.tex002} position={[-113.885, 0, 0]} />
            <mesh name="cube_outside_5_fracturepart" geometry={nodes.cube_outside_5_fracturepart.geometry} material={materials.tex009} position={[0, 0, -113.885]} />
            <mesh name="cube_outside_6_fracturepart" geometry={nodes.cube_outside_6_fracturepart.geometry} material={materials.tex008} position={[0, 0, 113.885]} />
          </group>
          <group name="logo" position={[5.164, -7.355, 45.665]} rotation={[-0.171, 0.55, -0.926]}>
            <mesh name="Mesh018" geometry={nodes.Mesh018.geometry} material={materials.logo} />
            <mesh name="Mesh018_1" geometry={nodes.Mesh018_1.geometry} material={materials.logo02} />
          </group>
        </group>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/ad-medica-cube.gltf')
